<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\InternalOperations.Application\InternalOperations.Application.csproj" />
    <ProjectReference Include="..\InternalOperations.Domain\InternalOperations.Domain.csproj" />
    <ProjectReference Include="..\InternalOperations.Shared\InternalOperations.Shared.csproj" />
  </ItemGroup>

</Project>
