<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\InternalOperations.Persistence\InternalOperations.Persistence.csproj" />
    <ProjectReference Include="..\..\src\InternalOperations.Persistence.Migrations.PostgreSql\InternalOperations.Persistence.Migrations.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\InternalOperations.Persistence.Migrations.SqlServer\InternalOperations.Persistence.Migrations.SqlServer.csproj" />
  </ItemGroup>

</Project>
