<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../InternalOperations.Persistence/InternalOperations.Persistence.csproj" />
    <ProjectReference Include="..\InternalOperations.Domain\InternalOperations.Domain.csproj" />
    <ProjectReference Include="..\InternalOperations.Shared\InternalOperations.Shared.csproj" />
  </ItemGroup>

</Project>
